import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import {
  createPlaylistRequest,
  deletePlaylistRequest,
  getPlaylistRequest,
  getPlaylistsRequest,
  getRadioPlaylistsRequest,
  updatePlaylistRequest,
} from '../requests/playlists.api';
import { isAxiosError } from 'axios';
import { ErrorResponse } from '../shared-types';

const PLAYLISTS_QUERY_KEY = 'playlists';
const PLAYLIST_QUERY_KEY = 'playlist';

export const usePlaylistsQuery = () => {
  return useQuery(
    [PLAYLISTS_QUERY_KEY],
    async () => await getPlaylistsRequest(),
    {
      onError: (error) => {
        if (isAxiosError<ErrorResponse>(error)) {
          console.log('🚀 ~ usePlaylistsQuery ~ error:', error.response?.data);
        }
      },
    }
  );
};

export const usePlaylistQuery = (id: number) => {
  return useQuery(
    [PLAYLIST_QUERY_KEY],
    async () => await getPlaylistRequest(id),
    {
      onError: (error) => {
        if (isAxiosError<ErrorResponse>(error)) {
          console.log('🚀 ~ usePlaylistQuery ~ error:', error.response?.data);
        }
      },
    }
  );
};

export const useRadioPlaylistsQuery = () => {
  return useQuery(
    [PLAYLISTS_QUERY_KEY, 'autoGenerated'],
    async () => await getRadioPlaylistsRequest(),
    {
      onError: (error) => {
        if (isAxiosError<ErrorResponse>(error)) {
          console.log(
            '🚀 ~ useRadioPlaylistsQuery ~ error:',
            error.response?.data
          );
        }
      },
    }
  );
};

export const useCreatePlaylistMutation = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: createPlaylistRequest,
    onSuccess: () => {
      queryClient.refetchQueries({ queryKey: [PLAYLISTS_QUERY_KEY] });
    },
    onError: () => {
      console.log('create playlist failed');
    },
  });
};

export const useUpdatePlaylistMutation = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: updatePlaylistRequest,
    onSuccess: () => {
      queryClient.refetchQueries({ queryKey: [PLAYLISTS_QUERY_KEY] });
    },
    onError: () => {
      console.log('update playlist failed');
    },
  });
};

export const useDeletePlaylistMutation = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: deletePlaylistRequest,
    onSuccess: () => {
      queryClient.refetchQueries({ queryKey: [PLAYLISTS_QUERY_KEY] });
    },
    onError: () => {
      console.log('delete playlist failed');
    },
  });
};
