import { API_URL } from '@env';
import { AxiosInterceptor } from '../AxiosInterceptor';
import { SongWithAlbumImage } from './songs.api';

const playlistsUrl = `${API_URL}/playlists`;

export interface Playlist {
  id: number;
  name: string;
  userId: number;
  autoGenerated: boolean;
  createdAt: Date | string;
  updatedAt: Date | string;
  songs: SongWithAlbumImage[];
}

export const getPlaylistsRequest = async () => {
  const axios = AxiosInterceptor.Instance;

  return (await axios.get<Playlist[]>(`${playlistsUrl}`)).data;
};

export const createPlaylistRequest = async (playlistName: string) => {
  const axios = AxiosInterceptor.Instance;

  return (await axios.post(`${playlistsUrl}`, { name: playlistName })).data;
};
